"""Stable event priorities for deterministic same-time signal ordering."""

GARDEN_PHASE_EVENT_PRIORITY = 10
GARDEN_EVALUATION_FINALIZE_TRIGGER_PRIORITY = 20
GARDEN_EVALUATION_FINALIZED_EVENT_PRIORITY = 25
GARDEN_INPUT_SIGNAL_EVENT_PRIORITY = 30
HEARTBEAT_EVENT_PRIORITY = 40
RRI_MEASUREMENT_EVENT_PRIORITY = 50
SIMULATION_COMPLETE_EVENT_PRIORITY = 100
